config/routes.rb
Rails.application.routes.draw do
  # As a user, I can list tasks
  get '/tasks', to: 'tasks#index'
  # As a user, I can add a new task
  get 'tasks/new', to: "tasks#new", as: :new_task
  post 'tasks', to: "tasks#create"
  # As a user, I can view the details of a task
  get 'tasks/:id', to: 'tasks#show', as: :task
  # As a user, I can edit a task (mark as completed / update title & details)
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  # As a user, I can remove a task
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params[:task].permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<br>
<br>
<br>

<h1>Edit '<%= @task.title %>' </h1>
<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task) %>
    </li>
  <% end %>
</ul>

<%= link_to "Create new task", new_task_path %>

app/views/tasks/new.html.erb
<br>
<br>
<br>

<h1>Create a new task</h1>
<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<ul>
  <li>Details: <%= @task.details %></li>
  <li>Completed: <%= @task.completed %></li>
</ul>

<%= link_to '<back', tasks_path %>
<br>
<%= link_to 'edit task', edit_task_path %>
<br>
<%= link_to 'delete task', destroy_task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>